project_id = "rvutjdrjxuilmjugnbtq"

[functions.registrar-ingreso]
verify_jwt = false

[functions.cancelar-ingreso]
verify_jwt = false

[functions.cancelar-compra-inventario]
verify_jwt = false

[functions.registrar-egreso]
verify_jwt = false

[functions.cancelar-egreso]
verify_jwt = false

[functions.simular-depreciaciones-historicas]
verify_jwt = false

[functions.limpiar-depreciaciones-simuladas]
verify_jwt = false
